# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from group import Group


class TestHRM():
    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def login(self, group):
        self.driver.find_element(By.CSS_SELECTOR, "#divUsername > .form-hint").click()
        self.driver.find_element(By.ID, "txtUsername").send_keys(group.username)
        self.driver.find_element(By.ID, "txtPassword").send_keys(group.password)
        self.driver.find_element(By.ID, "txtPassword").send_keys(Keys.ENTER)

    def test_hRM(self):
        self.driver.get("http://hrm.seleniumminutes.com/symfony/web/index.php/auth/login")
        self.login(Group(username = "admin", password = "Password"))

    def teardown_method(self, method):
        self.driver.quit()
