# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

class TestHRM():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_hRM(self):
    self.driver.get("http://hrm.seleniumminutes.com/symfony/web/index.php/auth/login")
    self.driver.find_element(By.CSS_SELECTOR, "#divUsername > .form-hint").click()
    self.driver.find_element(By.ID, "txtUsername").send_keys("admin")
    self.driver.find_element(By.ID, "txtPassword").send_keys("Password")
    self.driver.find_element(By.ID, "txtPassword").send_keys(Keys.ENTER)
